// <auto-generated />
using FormulaOneServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOneServer.Migrations
{
    [DbContext(typeof(FormulaDbContext))]
    [Migration("20250727210508_fixed_driver_info")]
    partial class fixed_driver_info
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("FormulaOneServer.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Helmet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfGPs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorldChampionships")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/red-bull-racing.png",
                            Country = "Netherlands",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/verstappen",
                            DriverName = "Max Verstappen",
                            DriverNumber = 1,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/verstappen",
                            NumberOfGPs = 213,
                            Team = "Red Bull Racing",
                            WorldChampionships = 4
                        },
                        new
                        {
                            Id = 2,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/red-bull-racing.png",
                            Country = "Japan",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/tsunoda",
                            DriverName = "Yuki Tsunoda",
                            DriverNumber = 22,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/tsunoda",
                            NumberOfGPs = 91,
                            Team = "Red Bull Racing",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 3,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/ferrari.png",
                            Country = "Monaco",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/leclerc",
                            DriverName = "Charles Leclerc",
                            DriverNumber = 16,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/leclerc",
                            NumberOfGPs = 151,
                            Team = "Ferrari",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 4,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/ferrari.png",
                            Country = "United Kingdom",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hamilton",
                            DriverName = "Lewis Hamilton",
                            DriverNumber = 44,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/hamilton",
                            NumberOfGPs = 360,
                            Team = "Ferrari",
                            WorldChampionships = 7
                        },
                        new
                        {
                            Id = 5,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mclaren.png",
                            Country = "Australia",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/piastri",
                            DriverName = "Oscar Piastri",
                            DriverNumber = 81,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/piastri",
                            NumberOfGPs = 50,
                            Team = "McLaren",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 6,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mclaren.png",
                            Country = "United Kingdom",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/norris",
                            DriverName = "Lando Norris",
                            DriverNumber = 4,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/norris",
                            NumberOfGPs = 132,
                            Team = "McLaren",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 7,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mercedes.png",
                            Country = "United Kingdom",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/russell",
                            DriverName = "George Russel",
                            DriverNumber = 63,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/russell",
                            NumberOfGPs = 132,
                            Team = "Mercedes",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 8,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mercedes.png",
                            Country = "Italy",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/antonelli",
                            DriverName = "Andrea Kimi Antoneli",
                            DriverNumber = 12,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/antonelli",
                            NumberOfGPs = 4,
                            Team = "Mercedes",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 9,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/aston-martin.png",
                            Country = "Canada",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/stroll",
                            DriverName = "Lance Stroll",
                            DriverNumber = 18,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/stroll",
                            NumberOfGPs = 170,
                            Team = "Aston Martin",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 10,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/aston-martin.png",
                            Country = "Spain",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/alonso",
                            DriverName = "Fernando Alonso",
                            DriverNumber = 14,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/alonso",
                            NumberOfGPs = 407,
                            Team = "Aston Martin",
                            WorldChampionships = 2
                        },
                        new
                        {
                            Id = 11,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/williams.png",
                            Country = "Thailand",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/albon",
                            DriverName = "Alexander Albon",
                            DriverNumber = 23,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/albon",
                            NumberOfGPs = 108,
                            Team = "Williams",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 12,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/williams.png",
                            Country = "Spain",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/sainz",
                            DriverName = "Carlos Sainz",
                            DriverNumber = 55,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/sainz",
                            NumberOfGPs = 210,
                            Team = "Williams",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 13,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/alpine.png",
                            Country = "France",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2025Drivers/gasly",
                            DriverName = "Pierre Gasly",
                            DriverNumber = 10,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/gasly",
                            NumberOfGPs = 157,
                            Team = "Alpine",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 14,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/alpine.png",
                            Country = "Australia",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/doohan",
                            DriverName = "Jack Doohan",
                            DriverNumber = 7,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/doohan",
                            NumberOfGPs = 5,
                            Team = "Alpine",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 15,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/haas.png",
                            Country = "France",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/ocon",
                            DriverName = "Esteban Ocon",
                            DriverNumber = 31,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/ocon",
                            NumberOfGPs = 160,
                            Team = "Haas",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 16,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/haas.png",
                            Country = "United Kingdom",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/bearman",
                            DriverName = "Oliver Bearman",
                            DriverNumber = 87,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/bearman",
                            NumberOfGPs = 7,
                            Team = "Haas",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 17,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/kick-sauber.png",
                            Country = "Germany",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hulkenberg",
                            DriverName = "Nico Hulkenberg",
                            DriverNumber = 27,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/hulkenberg",
                            NumberOfGPs = 231,
                            Team = "Kick Sauber",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 18,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/kick-sauber.png",
                            Country = "Brazil",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/bortoleto",
                            DriverName = "Gabriel Bortoleto",
                            DriverNumber = 5,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/bortoleto",
                            NumberOfGPs = 4,
                            Team = "Kick Sauber",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 19,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/racing-bulls.png",
                            Country = "France",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hadjar",
                            DriverName = "Isack Hadjar",
                            DriverNumber = 6,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/hadjar",
                            NumberOfGPs = 4,
                            Team = "Racing Bulls",
                            WorldChampionships = 0
                        },
                        new
                        {
                            Id = 20,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/racing-bulls.png",
                            Country = "New Zealand",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/lawson",
                            DriverName = "Liam Lawson",
                            DriverNumber = 30,
                            Helmet = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1024/fom-website/manual/Helmets2025/lawson",
                            NumberOfGPs = 15,
                            Team = "Racing Bulls",
                            WorldChampionships = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
