// <auto-generated />
using FormulaOneServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOneServer.Migrations
{
    [DbContext(typeof(FormulaDbContext))]
    [Migration("20250123080618_AddedAllF1DriversAsSeedData")]
    partial class AddedAllF1DriversAsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("FormulaOneServer.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/red-bull-racing.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/verstappen",
                            DriverName = "Max Verstappen",
                            DriverNumber = 1,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            Id = 2,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/red-bull-racing.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/lawson",
                            DriverName = "Liam Lawson",
                            DriverNumber = 30,
                            Team = "Red Bull Racing"
                        },
                        new
                        {
                            Id = 3,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/ferrari.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/leclerc",
                            DriverName = "Charles Leclerc",
                            DriverNumber = 16,
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 4,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/ferrari.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hamilton",
                            DriverName = "Lewis Hamilton",
                            DriverNumber = 44,
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 5,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mclaren.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/piastri",
                            DriverName = "Oscar Piastri",
                            DriverNumber = 81,
                            Team = "McLaren"
                        },
                        new
                        {
                            Id = 6,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mclaren.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/norris",
                            DriverName = "Lando Norris",
                            DriverNumber = 4,
                            Team = "McLaren"
                        },
                        new
                        {
                            Id = 7,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mercedes.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/russell",
                            DriverName = "George Russel",
                            DriverNumber = 63,
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 8,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/mercedes.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/antonelli",
                            DriverName = "Andrea Kimi Antoneli",
                            DriverNumber = 12,
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 9,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/aston-martin.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2024Drivers/stroll",
                            DriverName = "Lance Stroll",
                            DriverNumber = 18,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            Id = 10,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/aston-martin.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/alonso",
                            DriverName = "Fernando Alonso",
                            DriverNumber = 14,
                            Team = "Aston Martin"
                        },
                        new
                        {
                            Id = 11,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/williams.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/albon",
                            DriverName = "Alexander Albon",
                            DriverNumber = 23,
                            Team = "Williams"
                        },
                        new
                        {
                            Id = 12,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/williams.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/sainz",
                            DriverName = "Carlos Sainz",
                            DriverNumber = 55,
                            Team = "Williams"
                        },
                        new
                        {
                            Id = 13,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/alpine.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/gasly",
                            DriverName = "Pierre Gasly",
                            DriverNumber = 10,
                            Team = "Alpine"
                        },
                        new
                        {
                            Id = 14,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/alpine.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/fom-website/drivers/2024Drivers/doohan",
                            DriverName = "Jack Doohan",
                            DriverNumber = 7,
                            Team = "Alpine"
                        },
                        new
                        {
                            Id = 15,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/haas.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/ocon",
                            DriverName = "Esteban Ocon",
                            DriverNumber = 31,
                            Team = "Haas"
                        },
                        new
                        {
                            Id = 16,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/haas.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2024Drivers/bearman",
                            DriverName = "Oliver Bearman",
                            DriverNumber = 87,
                            Team = "Haas"
                        },
                        new
                        {
                            Id = 17,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/kick-sauber.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hulkenberg",
                            DriverName = "Nico Hulkenberg",
                            DriverNumber = 27,
                            Team = "Kick Sauber"
                        },
                        new
                        {
                            Id = 18,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/kick-sauber.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/bortoleto",
                            DriverName = "Gabriel Bortoleto",
                            DriverNumber = 5,
                            Team = "Kick Sauber"
                        },
                        new
                        {
                            Id = 19,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/racing-bulls.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2025Drivers/hadjar",
                            DriverName = "Isack Hadjar",
                            DriverNumber = 6,
                            Team = "Racing Bulls"
                        },
                        new
                        {
                            Id = 20,
                            CarImageLink = "https://media.formula1.com/d_team_car_fallback_image.png/content/dam/fom-website/teams/2025/racing-bulls.png",
                            DriverImageLink = "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/tsunoda",
                            DriverName = "Yuki Tsunoda",
                            DriverNumber = 22,
                            Team = "Racing Bulls"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
