// <auto-generated />
using FormulaOneServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOneServer.Migrations
{
    [DbContext(typeof(FormulaDbContext))]
    partial class FormulaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("FormulaOneServer.Models.Driver", b =>
                {
                    b.Property<int>("DriverNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DriverNumber");

                    b.ToTable("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
